# Generated by Django 5.0.4 on 2024-04-25 14:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='abstract',
            field=models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='abstract'),
        ),
        migrations.AddField(
            model_name='post',
            name='pic',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
