# Generated by Django 5.0.6 on 2024-05-15 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_professor'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='slug',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
