# Generated by Django 5.0.6 on 2024-05-15 06:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_professor_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='slug',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
