# Generated by Django 5.0.4 on 2024-05-16 05:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0004_alter_professor_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.IntegerField(unique=True)),
                ('time', models.CharField(max_length=20)),
                ('credit', models.IntegerField()),
                ('description', models.TextField(max_length=400)),
                ('sweetScale', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
            ],
        ),
    ]
