# Generated by Django 5.0.4 on 2024-05-16 07:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0005_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='sweetScale',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
