# Generated by Django 5.0.4 on 2024-05-16 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0006_alter_course_sweetscale'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='pic',
            field=models.ImageField(blank=True, default='', upload_to='images/'),
        ),
    ]
