# Generated by Django 5.0.6 on 2024-05-19 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0007_professor_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('description', models.TextField(max_length=400)),
                ('pic', models.ImageField(blank=True, default='', upload_to='images/location/')),
            ],
        ),
        migrations.AlterField(
            model_name='professor',
            name='description',
            field=models.CharField(max_length=400),
        ),
    ]
