# Generated by Django 5.0.4 on 2024-05-17 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0007_professor_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=400)),
                ('pic', models.ImageField(default='', upload_to='facilities/')),
            ],
        ),
        migrations.AlterField(
            model_name='professor',
            name='pic',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
