# Generated by Django 5.0.6 on 2024-05-19 12:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0008_location_alter_professor_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='slug',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
