# Generated by Django 5.0.4 on 2024-05-20 06:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0008_facility_alter_professor_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='area',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)]),
        ),
    ]
