# Generated by Django 5.0.6 on 2024-05-20 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0009_facility_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='description',
            field=models.TextField(max_length=400),
        ),
    ]
