# Generated by Django 5.0.4 on 2024-05-26 08:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0010_alter_professor_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='coolScale',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='course',
            name='sweetScale',
            field=models.CharField(max_length=20),
        ),
    ]
