# Generated by Django 5.0.4 on 2024-05-15 11:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_post_abstract_post_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='pic',
            field=models.ImageField(blank=True, default='', upload_to='images/'),
        ),
        migrations.CreateModel(
            name='MoodPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(default='不告訴你', max_length=50)),
                ('message', models.TextField()),
                ('del_pass', models.CharField(max_length=50)),
                ('pub_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('enabled', models.BooleanField(default=False)),
                ('mood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.mood')),
            ],
        ),
    ]
